#  Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Prepare RHEL and Rocky nodes

- name: Add epel-release repo
  package:
    name: epel-release
    state: present
  tags: install
  when: os_supported_redhat not in compute_os

- name: Add elrepo GPG key
  rpm_key:
    state: present
    key: "{{ elrepo_gpg_key_url }}"
  register: elrepo_gpg_key
  until: elrepo_gpg_key is not failed
  retries: "{{ max_retries }}"
  delay: "{{ max_delay }}"
  tags: install
  when: os_supported_redhat not in compute_os

- name: Add elrepo (nvidia kmod drivers)
  package:
    name: "{{ elrepo_rpm_url }}"
    state: present
  register: elrepo
  until: elrepo is not failed
  retries: "{{ max_retries }}"
  delay: "{{ max_delay }}"
  tags: install
  when: os_supported_redhat not in compute_os

- name: Permanently Disable swap
  mount:
    name: "swap"
    fstype: swap
    state: absent

- name: Disable selinux
  selinux:
    state: disabled
  tags: install

- name: Install common packages
  package:
    name: "{{ common_packages }}"
    state: present
  when: os_supported_centos not in compute_os
  tags: install

- name: Install common packages for CentOS 7.9
  package:
    name: "{{ common_packages_centos }}"
    state: present
  when: os_supported_centos in compute_os

- name: Install common packages for non leap and non RHEL OS
  package:
    name: "{{ common_packages_non_leap }}"
    state: present
  tags: install
  when: os_supported_redhat not in compute_os

- name: Install common packages for RHEL
  package:
    name: "{{ common_packages_rhel }}"
    state: present
  tags: install
  when: os_supported_redhat in compute_os