#  Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Add leap repos
  zypper_repository:
    name: "{{ item.name }}"
    repo: "{{ item.repo }}"
    state: present
    autorefresh: yes
  with_items:
    - "{{ leap_repo }}"
  tags: install

- name: Installing python-xml
  package:
    name: python-xml
    state: present
  tags: install

- name: Add nvidia repo
  zypper_repository:
    name: NVIDIA
    repo: "{{ nvidia_repo }}"
    state: present
    disable_gpg_check: yes
    auto_import_keys: yes
    autorefresh: yes
  tags: install

- name: Install nvidia(This might take 10-15 minutes)
  command: zypper --gpg-auto-import-keys install -l -y x11-video-nvidiaG06
  changed_when: true
  tags: install

- name: Permanently Disable swap
  mount:
    name: "swap"
    fstype: swap
    state: absent
  tags: install

- name: Install common packages
  package:
    name: "{{ common_packages }}"
    state: present
  tags: install


- name: Installing dkms
  package:
    name: dkms
    state: present
  changed_when: true
  tags: install

- name: Add AMD ROCm repository for leap
  zypper_repository:
    name: rocm
    repo: "{{ amd_repo }}"
    state: present
  failed_when: false
  tags: install

- name: Import gpg-key for installing AMD ROCm
  rpm_key:
    key: "{{ gpg_key_amd }}"
    state: present
  tags: install

- name: Install AMD ROCm drivers
  ansible.builtin.expect:
    command: zypper install rocm-dkms
    responses:
        (.*) [1/2/c/d/?](.): '2'
        (.*)(y): 'y'
  tags: install

- name: Allowing modules
  copy:
    src: module.conf
    dest: "{{ amd_gpu_dest }}"
    owner: root
    group: root
    mode: "{{ conf_file_mode }}"
  tags: install

- name: Enable the modules amdgpu
  modprobe:
    name: amdgpu
    state: present
  tags: install
    
- name: Reboot after installing GPU drivers
  reboot:
  tags: install