# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Set fact for BMC NIC IP and netmask details
  ansible.builtin.set_fact:
    bmc_nic: "{{ admin_nic }}"
    bmc_nic_ip: "{{ omnia_bmc_ip }}"
    bmc_nic_netmask: "{{ omnia_bmc_netmask }}"

- name: Set fact for BMC NIC IP and netmask details
  ansible.builtin.set_fact:
    admin_nic_ip: "{{ omnia_admin_ip }}"
    admin_nic_netmask: "{{ omnia_admin_netmask }}"

- name: Validate pxe_subnet
  ansible.builtin.fail:
    msg: "{{ pxe_subnet_msg }}"
  when:
    - discovery_mechanism == discovery_method_bmc
    - admin_nic_subnet != pxe_subnet

- name: Configure the admin and bmc nic
  ansible.builtin.include_tasks: "{{ role_path }}/../xcat/tasks/mtms/enable_nic_configuration.yml"
