# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: BMC Discover on Dynamic ranges
  ansible.builtin.shell: |
      bmcdiscover --range '{{ bmc_dynamic_start_range }}'-'{{ bmc_dynamic_end_range.split('.')[-1] }}' -z -w > '{{ dynamic_ip_file }}'
  register: dynamic_discovery
  changed_when: false

- name: Assert dynamic discovery
  ansible.builtin.assert: 
    that:
      - " '{{ no_bmc_found }}' not in dynamic_discovery.stderr"
    fail_msg: "{{ dynamic_discovery_fail_msg }}"
