# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Update IPMI table and create genesis image
  block:
    - name: Update IPMI table
      ansible.builtin.include_tasks: update_xcat_passwd_mtms.yml

    - name: Update network table for BMC network
      ansible.builtin.include_tasks: update_xcat_network_mtms.yml
      when: bmc_dynamic_status

    - name: Create genesis image
      ansible.builtin.include_tasks: create_genesis_image.yml

    - name: Perform operations for static range
      block:
        - name: Perform BMC Discover on static range
          ansible.builtin.include_tasks: bmc_static_discovery.yml

        - name: Create database for static bmc mode
          ansible.builtin.include_tasks: update_db_static.yml

        - name: Update node objects for static bmc mode
          ansible.builtin.include_tasks: update_node_obj.yml
          
        - name: Provision static nodes
          ansible.builtin.include_tasks: set_provision_image_mtms.yml
          with_items: "{{ bmc_node_group }}"
      when: bmc_static_status
      
    - name: Perform operations for dynamic range
      block:
        - name: Wait for "{{ dhcp_timeout }}" before starting dynamic discovery
          ansible.builtin.wait_for:
            timeout: "{{ dhcp_timeout }}"

        - name: Perform BMC Discover on dynamic range
          ansible.builtin.include_tasks: bmc_dynamic_discovery.yml

        - name: Enable IPMI on dynamic iDRACs
          ansible.builtin.include_tasks: dynamic_ipmi_enable.yml

        - name: Update node objects for dynamic bmc_mode
          ansible.builtin.include_tasks: update_db_dynamic.yml

        - name: Update node objects for static bmc mode
          ansible.builtin.include_tasks: update_node_obj.yml
          
        - name: Fetch all the dhcp enabled nodes
          ansible.builtin.include_tasks: fetch_dynamic_nodes.yml

        - name: Provision dynamic nodes
          ansible.builtin.include_tasks: set_provision_image_mtms.yml
          with_items: "{{ dynamic_nodes }}"
      when: bmc_dynamic_status
      
    - name: Assert for successful static and dynamic discovery
      ansible.builtin.assert:
        that:
          - "('{{ no_bmc_found }}' not in static_discovery.stderr) or ('{{ no_bmc_found }}' not in dynamic_discovery.stderr)"
        fail_msg: "{{ static_dynamic_fail_msg }}"
      when:
        - bmc_static_status
        - bmc_dynamic_status

  when: discovery_mechanism | lower == discovery_method_bmc
