# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Task for set PXE to nodes for mtms
  block:
    - name: Set PXE to node object for mtms
      ansible.builtin.command: rsetboot {{ item }} net
      changed_when: true
      register: set_pxe_bmc
  rescue:
    - name: Verify set node object is successful for mapping
      ansible.builtin.debug:
        msg: "{{ mtms_set_pxe_warning_msg }} {{ set_pxe_bmc.stderr }}"
      when: set_pxe_bmc.stderr is defined
  when: discovery_mechanism | lower == discovery_method_bmc


- name: Task to reboot the nodes for BMC
  block:
    - name: Reboot nodes
      ansible.builtin.command: rpower {{ item }} reset
      changed_when: true
      register: reboot_status

    - name: Installation status for bmc - provision.yml
      ansible.builtin.debug:
        msg: "{{ mtms_xcat_install_success_msg }}"
  rescue:
    - name: Verify set node object is successful for mapping
      ansible.builtin.debug:
        msg: "{{ mtms_reboot_warning_msg }} {{ reboot_status.stderr }}"
      when: reboot_status.stderr is defined
  when: discovery_mechanism | lower == discovery_method_bmc
