apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /work/k8s/jhub-db
  persistentVolumeReclaimPolicy: Retain

