# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

#### NIC Details for Control Plane
## Public NIC Details
# The nic/ethernet card that is connected to the public internet.
# Mandatory
public_nic: "eno2"

## Admin NIC Details
# TBD
# Default value: "eno1"
# Mandatory
admin_nic: "eno1"

# TBD
# Default value: "172.29.0.0"
# Mandatory
admin_nic_subnet: "172.29.0.0"

### PXE NIC Details
# This NIC will provide provisioning route information
# Default value: "eno1"
# Mandatory
pxe_nic: "eno1"

# The dhcp range for assigning the IPv4 address while provisioning
# Mandatory
pxe_nic_start_range: "172.29.0.100"
pxe_nic_end_range: "172.29.0.200"

### IB NIC Details
# If provided, omnia will handle and assign static IPs to compute node's IB network.
# TBD
# Optional
ib_nic_subnet: ""

### BMC NIC Details
# If provided, omnia will handle and assign static IPs to the iDRACs.
# Optional
bmc_nic_subnet: ""

#### PXE provisioned nodes information source
## PXE mapping file path details
# The mapping file consists of the MAC address and its respective IP address and Hostname.
# If user wants to assign static IPs, format of csv: MAC,Hostname,IP
# Ex. xx:yy:zz:aa:bb,server,172.17.0.5
# A templates for mapping file exists in omnia/examples and is named as host_mapping_file_os_provisioning.csv
# This depicts the path where user has kept the mapping file for DHCP configurations.
# Optional ( Either pxe_mapping_file_path or PXE switch details should to be provided )
pxe_mapping_file_path: ""

# Switch details
# TBD
# PXE switch that will be connected to all iDRACs for provisioning
# Optional ( Either pxe_mapping_file_path or PXE switch details should to be provided )
pxe_switch_ip: ""
pxe_switch_snmp_community_string: "public"

# TBD
node_name: "compute"
