# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# This config file will be used for deploying k8s roce plugin.


# Define network interfaces with their respective IP ranges and gateways which should be assigned inside the pod in this dictionary
# Number of entries in this dictionary should be equal to number of bcm roce interfaces which must be used for roce pod.
# VLAN nics are not supported for roce plugin deployment
# name: The name of the interface of the roce nic
# range: The IP range for this interface which should be assigned inside rocepod
# gateway: The gateway for this interface which should be assigned inside rocepod
interfaces:
  - name: eth1
    range: 192.168.1.0/24
    gateway: 192.168.1.1
  - name: eth2
    range: 192.168.2.0/24
    gateway: 192.168.2.1
  - name: eth3
    range: 192.168.3.0/24
    gateway: 192.168.3.1
  - name: eth4
    range: 192.168.4.0/24
    gateway: 192.168.4.1
  - name: eth5
    range: 192.168.5.0/24
    gateway: 192.168.5.1
  - name: eth6
    range: 192.168.6.0/24
    gateway: 192.168.6.1
  - name: eth7
    range: 192.168.7.0/24
    gateway: 192.168.7.1
  - name: eth8
    range: 192.168.8.0/24
    gateway: 192.168.8.1