# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

#***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.                  
# SIMPLY APPEND THE REQUIRED VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
#***********************************************************************

# This variable is used to enable iDRAC telemetry support
# Accepted values:  true or false
idrac_telemetry_support: false

# This variable is used to start or stop omnia telemetry
# Accepted values:  true or false
# If omnia_telemetry_support is true, then at least one of collect_regular_metrics or collect_health_check_metrics or collect_gpu_metrics should be true, to collect metrics
# If omnia_telemetry_support is false, telemetry acquisition will be stopped
omnia_telemetry_support: false

# This variable is used to enable visualizations on grafana
# Accepted values:  true or false
visualization_support: false

##### BELOW VARIABLES ARE MANDATORY IF EITHER idrac_telemetry_support OR omnia_telemetry_support OR visualization_support IS true
# Kubernetes pod network CIDR for appliance k8s network
# Make sure this value does not overlap with any of the host networks.
# Default value: "192.168.0.0/16"
appliance_k8s_pod_net_cidr: "192.168.0.0/16"

# These addresses will be used by Loadbalancer for assigning External IPs to K8s services(Timescaledb and Grafana)
# If pod_external_ip_start_range: "x.y.240.100" and pod_external_ip_end_range: "x.y.240.105" and 
# If admin_nic_subnet provided in provision_config.yml is 10.5.0.0, pod_external_ip_start_range will be 10.5.240.100 and pod_external_ip_end_range will be 10.5.240.105
# Make sure the IP range is not assigned to any node in the cluster.
# First and Second octet values are neither validated nor used by Omnia. Instead they will be calculated internally by Omnia from admin_nic_subnet provided in provision_config.yml
# Only third and fourth octet values will be validated and used for External IPs
# The third octet value of pod_external_ip_end_range should be greater than or equal to third octet value of pod_external_ip_start_range.
# The fourth octet value of pod_external_ip_end_range should be greater than fourth octet value of pod_external_ip_start_range when third octet values are same
pod_external_ip_start_range: "x.y.240.100"
pod_external_ip_end_range: "x.y.240.105"

# Username used for connecting to timescale db
# The username must not contain -,\, ',"
# The Length of the username should be at least 2 characters.
# Mandatory field
timescaledb_user: "omnia"

# Password used for connecting to timescale db
# The password must not contain -,\, ',",@
# The Length of the password should be at least 2 characters.
# Mandatory field
timescaledb_password: ""

##### BELOW VARIABLES ARE MANDATORY WHEN idrac_telemetry_support IS SET TO true
# The username for idrac
# The username must not contain -,\, ',"
# Required only if idrac_telemetry_support is true
idrac_username: ""

# Password used for idrac
# The password must not contain -,\, ',"
# Required only if idrac_telemetry_support is true
idrac_password: ""

### ADVANCE CONFIGURATIONS FOR IDRAC TELEMETRY ###
# Username used for connecting to mysql db
# The username must not contain -,\, ',"
# The Length of the username should be at least 2 characters.
# The username should not be kept 'root'.
# Mandatory field when idrac_telemetry_support is true
mysqldb_user: ""

# Password used for connecting to mysql db
# The password must not contain -,\, ',"
# The Length of the password should be at least 2 characters.
# Mandatory field when idrac_telemetry_support is true
mysqldb_password: ""

# Password used for connecting to timescale db for root user
# The password must not contain -,\, ',"
# The Length of the password should be at least 2 characters.
# Mandatory field when idrac_telemetry_support is true
mysqldb_root_password: ""

##### BELOW VARIABLES ARE MANDATORY WHEN omnia_telemetry_support IS SET TO true
# This variable denotes the time interval of telemetry data collection from required computue nodes
# This variable accepts input in seconds
# Default value is 300
# Example 1: omnia_telemetry_collection_interval: 300
# Example 2: omnia_telemetry_collection_interval: 600
# Valid range: minimum 60 seconds and maximum 3600 seconds(i.e. 1 minute to 1 hour)
omnia_telemetry_collection_interval: 300

# This variable is used to enable metric collection part of the regular metric group
# Accepted values:  true or false
collect_regular_metrics: true

# This variable is used to enable metric collection related to health check
# Accepted values:  true or false
collect_health_check_metrics: true

# This variable is used to enable metric collection related to GPU
# Accepted values:  true or false
collect_gpu_metrics: true

### ADVANCE CONFIGURATIONS FOR OMNIA TELEMETRY ###
# This variable is used to set an appropriate time interval for all compute nodes so that they do not congest the admin network
# A random number between 0 and fuzzy_offset gets added with omnia_telemetry_collection_interval value to decide individual compute node's telemetry data collection interval
# This variable accepts input in seconds
# Default value is 60
# Example 1: fuzzy_offset: 60
# Example 2: fuzzy_offset: 100
# For larger cluster this parameter can be set with higher value
# This value should be between 60 and omnia_telemetry_collection_interval value
fuzzy_offset: 60

# This variable is used to define data collection timeout period
# This variable accepts input in seconds
# Default value is 5
# Example 1: metric_collection_timeout: 5
# Example 2: metric_collection_timeout: 10
# This value should be greater than 0 and less than omnia_telemetry_collection_interval value
metric_collection_timeout: 5

##### BELOW VARIABLES ARE MANDATORY WHEN visualization_support IS SET TO true
# The username for grafana UI
# The length of username should be at least 5
# The username must not contain -,\, ',"
grafana_username: ""

# Password used for grafana UI
# The length of the password should be at least 5
# The password must not contain -,\, ',"
# The password should not be kept 'admin'
grafana_password: ""

# At this location grafana persistent volume will be created.
# If using telemetry, all telemetry related files will also be stored and
# both timescale and mysql databases will be mounted to this location.
# '/' is mandatory at the end of the path.
mount_location: "/opt/omnia/telemetry/"