#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
- name: Read software_config.json
  ansible.builtin.include_vars:
    file: "{{ software_config_file }}"
    name: software_config

- name: Load telemetry.json
  ansible.builtin.set_fact:
    telemetry_json: "{{ lookup('file', telemetry_json_file) | from_json }}"

# This will task will create a map of <package name> and <package_name-version> which is used in k8s_var.yml.j2
# telemetry_package_map = {
#   "calicoctl": "calicoctl-v3.27.3",
#   "etcd": "etcd-v3.5.12"
#   ..
# }
- name: Create a mapping of package name and version
  ansible.builtin.set_fact:
    telemetry_package_map: "{{ telemetry_package_map | default({}) | combine({ ((item.package).rsplit('-', 1)[0]): item.package}) }}"
  loop: "{{ telemetry_json['telemetry']['cluster'] }}"
  when: (item.type == "tarball" or item.type == "git")

- name: Extract k8s version
  ansible.builtin.set_fact:
    k8s_version: "{{ (telemetry_package_map['kubectl']).rsplit('-', 1)[1] | default('1.26.12') }}"
