---

- name: Initialize variables
  ansible.builtin.set_fact:
    add_kernel_param: false

- name: Include server_spec.yml
  block:
    - name: Include server_spec file
      ansible.builtin.include_vars: "{{ server_spec }}"
      register: include_server_spec
      no_log: true
      tags: init
  rescue:
    - name: Failed to include server_spec.yml
      ansible.builtin.fail:
        msg: "{{ server_spec_syntax_fail_msg }} Error: {{ include_server_spec.message }}"

- name: Parse server_spec data
  ansible.builtin.set_fact:
    category_data: "{{ category_data | default({}) | combine({item.key: item.value}) }}"
  with_dict: "{{ Categories }}"

- name: Set additional kernel parameter status
  block:
    - name: Set additional kernel parameter status
      ansible.builtin.set_fact:
        add_kernel_param: true
      with_dict: "{{ category_data }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.value is defined and item.value | map(attribute='os') | select('defined') | list | length > 0
  rescue:
    - name: Validating cmdline parameter
      ansible.builtin.debug:
        msg: " Kernel {{ item.key }} has invalid or missing cmdline parameter."
