#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---


# global
installation_success_status: "Pytorch succesfully installed"
installation_failed_status: "Failed to install pytorch"

# Validate inventory
fail_no_node_kube_node: "Failed. Pytorch software is present in software_config.json. No node is part of kube_node group in inventory"
fail_inv_format: "Failed. Pytorch software is present in software_config.json.
Invalid inventory format, specify kube_control_plane and kube_node."
fail_node_kube_control_plane: "Failed. Pytorch software is present in software_config.json.
There should be exactly one entry for kube_control_plane in the inventory"
pytorch_empty_inventory_fail_msg: |
  "Failed. Inventory not provided.
  Please re-run the playbook with an inventory that includes the groups 'kube_control_plane' and 'kube_node' by using the -i inventory option"

# For checking entry in software_config.json
pytorch_not_in_software_config: |
  "pytorch is not present in software_config.json.
  Please mention pytorch in software_config.json and execute pytorch.yml again"

# For env proxy setup
local_repo_access_path: "/opt/omnia/offline/local_repo_access.yml"

# Usage: check_prerequisites.yml for validate_software_config_json.yml
software_config_json_file: "{{ role_path }}/../../../input/software_config.json"
software_config_parameters_fail_msg: "Failed. Please ensure cluster_os_type, cluster_os_verion, repo_config are defined in software_config.json"

# Nvidia: check_prerequisites.yml
nvidia_container_toolkit: "nvidia-container-toolkit"

# pytorch.json file path
pytorch_json_file: "{{ role_path }}/../../../input/config/{{ cluster_os_type }}/{{ cluster_os_version }}/pytorch.json"

# Errors: check_prerequisites.yml
error_check_gpu_failed: "GPU Driver absent. Skipping pytorch installation."
error_check_container_engine_failed: "pytorch requires containerd as a prerequisite. Please execute scheduler.yml/omnia.yml and install k8s and execute
 pytorch again"
error_dri_file_failed: "Unable to read dri files in /dev/dri folder"


# check_prerequisites.yml - Create omnia folder if it doesn't exist
omnia_foler_path: "/opt/omnia"
omnia_foler_stat: "directory"
omnia_foler_mode: "0755"

# Errors: pytorch_install.yml
error_pull_container: "Unable to pull container image"
pytorch_cpu_definition_fail_msg: |
  "Failed. pytorch_cpu details is not defined in pytorch.json. Verify the pytorch.json and re-run the playbook."
pytorch_amd_definition_fail_msg: |
  "Failed. AMD GPU detected and pytorch_amd details is not defined in pytorch.json. Verify the pytorch.json and re-run the playbook."
pytorch_nvidia_definition_fail_msg: |
  "Failed. NVIDIA GPU detected and pytorch_nvidia details is not defined in pytorch.json. Verify the pytorch.json and re-run the playbook."
pytorch_gaudi_definition_fail_msg: |
  "Failed. Intel GAUDI GPU detected and pytorch_gaudi details is not defined in pytorch.json. Verify the pytorch.json and re-run the playbook."

# Usage: pytorch_verify.yml
example_src_file_path: "pytorch_example.py"
example_file_path: "/opt/omnia/pytorch_example.py"
example_file_owner: "root"
example_file_group: "root"
example_file_mode: "0755"

# Error: pytorch_verify.yml
error_example_failed: "Unable to execute pytorch sample model"
