#  Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Install nfs-utils
  ansible.builtin.package:
    name: nfs-utils
    state: present

- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Start and enable rpcbind and nfs-server service
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - rpcbind
    - nfs-server

- name: Adding NFS share entries in /etc/exports for manager
  ansible.builtin.lineinfile:
    path: "{{ exports_file_path }}"
    line: "{{ item.0.location }} {{ item.1 }}(rw,sync,no_root_squash)"
  with_nested:
    - "{{ pv_volumes }}"
    - "{{ groups['manager'] }}"

- name: Adding NFS share entries in /etc/exports for compute
  ansible.builtin.lineinfile:
    path: "{{ exports_file_path }}"
    line: "{{ item.0.location }} {{ item.1 }}(rw,sync,no_root_squash)"
  with_nested:
    - "{{ pv_volumes }}"
    - "{{ groups['compute'] }}"

- name: Adding NFS share entries in /etc/exports for compute
  ansible.builtin.lineinfile:
    path: "{{ exports_file_path }}"
    line: "{{ item.0.location }} {{ item.1 }}(rw,sync,no_root_squash)"
  with_nested:
    - "{{ pv_volumes }}"
    - "{{ groups['login'] }}"
  when:
    - groups['login'] is defined
    - groups['login'] | length | int > 0

- name: Exporting the shared directories
  ansible.builtin.command: exportfs -ra
  changed_when: true

- name: Configuring firewall
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ nfs_services }}"

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
