# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Include telemetry_config_file.yml
- name: Check that the telemetry_config.yml exists
  ansible.builtin.stat:
    path: "{{ telemetry_config_file }}"
  register: stat_result

- name: Fail if telemetry_config.yml file doesn't exist
  ansible.builtin.fail:
    msg: "{{ fail_msg_telemetry_config_file }}"
  when: not stat_result.stat.exists

- name: Check telemetry_config.yml file is encrypted
  ansible.builtin.command: cat {{ telemetry_config_file }}
  changed_when: false
  register: config_content
  no_log: true

- name: Decrpyt telemetry_login_vars.yml
  ansible.builtin.command: >-
    ansible-vault decrypt {{ telemetry_config_file }}
    --vault-password-file {{ vault_filename }}
  changed_when: false
  when: "'$ANSIBLE_VAULT;' in config_content.stdout"

- name: Include variable file telemetry_config.yml
  block:
    - name: Include variable file telemetry_config.yml
      ansible.builtin.include_vars: "{{ telemetry_config_file }}"
      register: include_telemetry_config
      no_log: true
  rescue:
    - name: Failed to include telemetry_config.yml
      ansible.builtin.fail:
        msg: "{{ telemetry_config_syntax_fail_msg }} Possible Syntax Error Hints: {{ include_telemetry_config.message }}"

- name: Set support values
  ansible.builtin.set_fact:
    idrac_telemetry_support: "{{ idrac_telemetry_support | lower }}"
    omnia_telemetry_support: "{{ omnia_telemetry_support | lower }}"
    visualization_support: "{{ visualization_support | lower }}"

- name: Assert idrac telemetry support
  ansible.builtin.assert:
    that:
      - idrac_telemetry_support == true or idrac_telemetry_support == false
    success_msg: "{{ idrac_telemetry_support_success_msg }}"
    fail_msg: "{{ idrac_telemetry_support_fail_msg }}"

- name: Assert omnia telemetry support
  ansible.builtin.assert:
    that:
      - omnia_telemetry_support == true or omnia_telemetry_support == false
    fail_msg: "{{ omnia_telemetry_support_fail_msg }}"

- name: Assert visualization support
  ansible.builtin.assert:
    that:
      - visualization_support == true or visualization_support == false
    success_msg: "{{ visualization_support_success_msg }}"
    fail_msg: "{{ visualization_support_fail_msg }}"

- name: Please wait, This task will take few seconds
  ansible.builtin.pause:
    seconds: "{{ idrac_omnia_telemetry_support_false_warn_time }}"
    prompt: "{{ idrac_omnia_telemetry_support_warn_msg }}"
  when: not idrac_telemetry_support and not omnia_telemetry_support

- name: Assert usernames and passwords in telemetry_login_vars.yml
  when: idrac_telemetry_support or omnia_telemetry_support
  block:
    - name: Assert timescaledb user name
      ansible.builtin.assert:
        that:
          - timescaledb_user | length > 1
          - '"-" not in timescaledb_user '
          - '"\\" not in timescaledb_user '
          - '"\"" not in timescaledb_user '
          - " \"'\" not in timescaledb_user "
      no_log: true

    - name: Assert timescaledb user password
      ansible.builtin.assert:
        that:
          - timescaledb_password | length > 1
          - '"-" not in timescaledb_password '
          - '"\\" not in timescaledb_password '
          - '"\"" not in timescaledb_password '
          - " \"'\" not in timescaledb_password "
          - '"@" not in timescaledb_password '
      no_log: true

  rescue:
    - name: Validation issue in telemetry_config.yml
      ansible.builtin.fail:
        msg: "{{ login_vars_fail_msg }}"

# Include validations for idrac telemetry
- name: Validate idrac telemetry
  ansible.builtin.include_tasks: validate_idrac_telemetry.yml
  when: idrac_telemetry_support

# Include validations for omnia telemetry
- name: Validate omnia telemetry
  ansible.builtin.include_tasks: validate_omnia_telemetry.yml
  when: omnia_telemetry_support

- name: Include grafana validations
  ansible.builtin.include_tasks: validate_grafana_params.yml
  when: visualization_support

- name: Set variable if k8s needs to be installed
  when: idrac_telemetry_support or omnia_telemetry_support or visualization_support
  block:
    - name: Check k8s is installed or not
      ansible.builtin.command: kubectl get pods -A
      changed_when: false
      failed_when: false
      register: k8s_pods

    - name: Validate k8s_pod_net_cidr
      when: "'nfs-client-provisioner' not in k8s_pods.stdout"
      block:
        - name: Assert kubernetes pod network CIDR
          ansible.builtin.assert:
            that:
              - appliance_k8s_pod_net_cidr | ansible.utils.ipv4
              - appliance_k8s_pod_net_cidr | length > 9
              - '"/" in appliance_k8s_pod_net_cidr '
            success_msg: "{{ success_msg_k8s_pod_network_cidr }}"
            fail_msg: "{{ fail_msg_k8s_pod_network_cidr }}"

        - name: Set kubernetes pod CIDR
          ansible.builtin.set_fact:
            k8s_net_cidr: "{{ appliance_k8s_pod_net_cidr }}"

- name: Set variable if metallb needs to be configured
  when: omnia_telemetry_support or idrac_telemetry_support or visualization_support
  block:
    - name: Register IPAddressPool output
      ansible.builtin.command: "kubectl get IPAddressPool -A"
      changed_when: false
      failed_when: false
      register: ipaddresspool_output

    - name: Validations for pod_external_ip_start_range and pod_external_ip_end_range
      when: "'metallb-system' not in ipaddresspool_output.stdout"
      block:
        - name: Validate format of pod_external_ip_start_range
          ansible.builtin.assert:
            that: pod_external_ip_start_range | regex_search('^[A-Za-z0-9]+\.[A-Za-z0-9]+\.\d+\.\d+$')
            fail_msg: "{{ validation_error_msg_format_start_range }}"
            success_msg: "{{ validation_success_msg_format_start_range }}"

        - name: Validate format of pod_external_ip_end_range
          ansible.builtin.assert:
            that: pod_external_ip_end_range | regex_search('^[A-Za-z0-9]+\.[A-Za-z0-9]+\.\d+\.\d+$')
            fail_msg: "{{ validation_error_msg_format_end_range }}"
            success_msg: "{{ validation_success_msg_format_end_range }}"

        - name: Split pod external IP ranges into octets
          ansible.builtin.set_fact:
            start_range_octets: "{{ pod_external_ip_start_range.split('.') }}"
            end_range_octets: "{{ pod_external_ip_end_range.split('.') }}"

        - name: Check if pod external IP range has 4 octets
          ansible.builtin.assert:
            that:
              - start_range_octets | length == 4
              - end_range_octets | length == 4
            fail_msg: "{{ validation_error_msg_4_octets }}"
            success_msg: "{{ validation_success_msg_4_octets }}"

        - name: Check if third and fourth octets of pod external IP are within 0 to 255
          ansible.builtin.assert:
            that:
              - 0 <= start_range_octets[2] | int <= 255
              - 0 <= start_range_octets[3] | int <= 255
              - 0 <= end_range_octets[2] | int <= 255
              - 0 <= end_range_octets[3] | int <= 255
            fail_msg: "{{ validation_error_msg_octet_range }}"
            success_msg: "{{ validation_success_msg_octet_range }}"

        - name: Check if third octet of pod external IP start range is less than or equal to third octet of end range
          ansible.builtin.assert:
            that:
              - start_range_octets[2] | int <= end_range_octets[2] | int
            fail_msg: "{{ validation_error_msg_octet_order }}"
            success_msg: "{{ validation_success_msg_octet_order }}"

        - name: Check if fourth octet of pod external IP start range is less than fourth octet of end range when third octets are the same
          ansible.builtin.assert:
            that:
              - start_range_octets[2] != end_range_octets[2] or start_range_octets[3] | int < end_range_octets[3] | int
            fail_msg: "{{ validation_error_msg_same_third_octet_order }}"
            success_msg: "{{ validation_success_msg_same_third_octet_order }}"

# Encrypt telemetry_config.yml
- name: Create ansible vault key
  ansible.builtin.set_fact:
    vault_key: "{{ lookup('password', '/dev/null chars=ascii_letters') }}"
  when: "'$ANSIBLE_VAULT;' not in config_content.stdout"

- name: Save vault key
  ansible.builtin.lineinfile:
    path: "{{ vault_filename }}"
    line: "{{ vault_key }}"
    mode: "{{ vault_file_perm }}"
    owner: root
    create: true
  when: "'$ANSIBLE_VAULT;' not in config_content.stdout"

- name: Encrypt telemetry_config.yml file
  ansible.builtin.command: >-
    ansible-vault encrypt {{ telemetry_config_file }}
    --vault-password-file {{ vault_filename }}
  changed_when: false
