---
- name: deploy ntpd
  yum: name=ntp state=present

- name: deploy ntpdate
  yum: name=ntpdate state=present

# ntp server
- name: update ntp servers
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: yes
  notify:
    - restart ntpd
    - sync clocks
