# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Configure postbootscripts
  ansible.builtin.command: chdef all postbootscripts="otherpkgs"
  changed_when: true

- name: Postscripts for RHEL/Rocky
  when:
    - control_plane_os in control_plane_os_redhat or
      control_plane_os in control_plane_os_rocky
  block:
    - name: Configure bmc postbootscripts
      ansible.builtin.include_tasks: configure_postscripts_bmc.yml
      when: bmc_postscripts_config_status

    - name: Configure ib postbootscripts
      ansible.builtin.include_tasks: configure_postscripts_ib.yml

    - name: Configure admin postbootscripts
      ansible.builtin.include_tasks: configure_postscripts_admin.yml

- name: Postscripts for ubuntu
  when:
    - control_plane_os in control_plane_os_ubuntu
  block:
    - name: Configure postscripts to configure hostname
      ansible.builtin.command: chdef all -p postbootscripts=omnia_hostname_ubuntu
      changed_when: true
