# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Setup postgres database
  ansible.builtin.command: "{{ pgsqlsetup_path }} -i -V"
  changed_when: true
  no_log: true
  environment:
    XCATPGPW: "{{ postgresdb_password }}"

- name: Start and enable xcat services in rhel/rocky
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ xcat_services }}"

- name: Create conf directory for postgresql in rhel/rocky
  ansible.builtin.file:
    path: "{{ postgresql_conf_dir }}"
    state: directory
    mode: "{{ file_permission }}"

- name: Copy postgresql.conf in rhel/rocky
  ansible.builtin.copy:
    src: "{{ postgresql_conf_src }}"
    dest: "{{ postgresql_conf_dest }}"
    mode: preserve

- name: Reload systemd
  ansible.builtin.systemd:
    daemon-reload: true
