# Copyright 2021 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Initialize variables
  set_fact:
    mngmnt_network_container_status: false
    mngmnt_network_container_image_status: false
    mngmnt_network_container_config_status: false
    backup_map_status: false
    new_node_status: false
  tags: install

- name: Check if any backup file exists
  block:
  - name: Check status of backup file
    stat:
      path: "{{ role_path }}/files/backup_mapping_file.csv"
    register: backup_map

  - name: Set status for backup file
    set_fact:
      backup_map_status: true
    when: backup_map.stat.exists == true  
  rescue:
  - name: Message
    debug:
      msg: "All nodes are new"
      verbosity: 2

- name: Inspect the mngmnt_network_container image
  command: "buildah images {{ mngmnt_network_image_name }}"
  register: mngmnt_network_container_image_result
  ignore_errors: true
  changed_when: false
  tags: install

- name: Check mngmnt_network_container status on the machine
  command: kubectl get pods -n network-config
  register: mngmnt_network_container_result
  ignore_errors: true
  changed_when: false
  tags: install

- name: Update mngmnt_network_container image status
  set_fact:
    mngmnt_network_container_image_status: true
  when: "'No such image' not in mngmnt_network_container_image_result.stderr"
  tags: install

- name: Update mngmnt_network_container container status
  set_fact:
    mngmnt_network_container_status: true
  when: "'mngmnt-network-container' in mngmnt_network_container_result.stdout"
  tags: install

- name: Update mngmnt_network_container  status
  set_fact:
    mngmnt_network_container_config_status: true
  when:
    - mngmnt_network_container_status == true