---
- name: restart ntpd
  service: name=ntpd state=restarted enabled=yes

- name: sync clocks
  command: ntpdc -np
  register: ntp_clock
  until:  ntp_clock.stdout.find('*') > -1
  retries: 10
  delay: 60