# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: main.yml
xcat_root_env: "/opt/xcat"
xcat_path_env: "/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools"
xcat_manpath_env: "/opt/xcat/share/man:$MANPATH"
perl_badlang_env: 0
xcat_role_vars:
  - "{{ role_path }}/vars/configuration.yml"
  - "{{ role_path }}/vars/mapping.yml"
  - "{{ role_path }}/vars/snmp.yml"
  - "{{ role_path }}/vars/mtms.yml"
  - "{{ role_path }}/vars/reprovision.yml"

# Usage: pre_requisites.yml
selinux_status_fail_msg: "selinux is not disabled. Disable it in /etc/sysconfig/selinux and reboot the system"
xcat_connection_search_key: "connection failure"

# Usage: package_installation.yml
ansible_galaxy_collection:
  - ansible.utils:2.5.2
  - community.general:4.8.7

common_packages_xcat:
  - createrepo
  - wget
  - unzip
  - bzip2
  - tar
python_version: python3.8
snmp_python_package: easysnmp
postgres_python_package: psycopg2-binary
requests_python_package: requests
pandas_python_package: pandas

# Usage: firewall_settings.yml
xcat_ports:
  - "3001/tcp"
  - "3001/udp"
  - "3002/tcp"
  - "3002/udp"
  - "3003/tcp"
  - "7/tcp"
  - "22/tcp"
  - "22/udp"
  - "873/tcp"
  - "873/udp"
  - "53/tcp"
  - "53/udp"
  - "67/tcp"
  - "67/tcp"
  - "68/tcp"
  - "68/udp"
  - "69/tcp"
  - "69/udp"
  - "80/tcp"
  - "80/udp"
  - "443/tcp"
  - "443/udp"
  - "88/tcp"
  - "88/udp"
  - "111/udp"
  - "514/tcp"
  - "514/udp"
  - "544/tcp"
  - "657/tcp"
  - "657/udp"
  - "782/tcp"
  - "1058/tcp"
  - "2049/tcp"
  - "2049/udp"
  - "4011/tcp"
  - "300/tcp"
  - "623/tcp"
  - "623/udp"
  - "161/tcp"
  - "161/udp"
  - "162/tcp"
  - "162/udp"
  - "5432/tcp"

# Usage: python_utility.yml
postgres_utility_path: "{{ role_path }}/files/utils/postgres_utility.py"

# Usage: install_xcat.yml
xcat_directory: /root/xcat
xcat_core_url: http://xcat.org/files/xcat/xcat-core/2.16.x_Linux/xcat-core/xcat-core-2.16.4-linux.tar.bz2
xcat_core_dest: "{{ xcat_directory }}/xcat-core-2.16.4-linux.tar.bz2"
xcat_dep_url: http://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-2.16.4-linux.tar.bz2
xcat_dep_dest: "{{ xcat_directory }}/xcat-dep-2.16.4-linux.tar.bz2"
xcat_packages:
  - xCAT
  - postgresql*
  - perl-DBD-Pg
file_permission: 0755
xcat_env_path: "/etc/profile.d/xcat.sh"
xcat_env_msg: "Saving xcat enviornment variables"
max_retries: 10

# Usage: create_node_inventory.yml
mapping_file_dest: "/tmp/mapping.csv"
provision_file_dest: "/opt/omnia/.data/provision.ini"
provision_file_msg: "/opt/omnia/.data/provision.ini doesn't exists, make sure you run provision.yml"

# Usage: create_mapping_file.yml
file_perm: 0644
ssh_search_key: "permission denied"

# Usage: assign_bmc_ip.yml
idrac_port: 443

# Usage: assign_hostname.yml
node_inventory_path: /opt/omnia/node_inventory

# Usage: create_mapping_file.yml
ping_search_key: "100% packet loss"

# Usage: initiate_monitor_status.yml
psql_devel_packages:
  - postgresql-devel
  - python3-devel
