# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: update_ipmi_table.yml
ipmi_success_msg: "Successfully updated IPMI table"
ipmi_fail_msg: "Failed creating genesis image"

# Usage: create_genesis_image.yml
genesis_path: "/tftpboot/xcat/genesis.kernel.x86_64"
control_plane_arch: "x86_64"

# Usage: main.yml
discovery_method_bmc: "bmc"
dhcp_timeout: 180

#Usage: bmc_static_discovery.yml
static_ip_file: "/opt/omnia/static.stanzas"
static_discovery_fail_msg: "Failed to discover any idrac's with the static range. Please check the range again"

#Usage: bmc_dynamic_discovery.yml
dynamic_ip_file: "/opt/omnia/dynamic.stanzas"
dynamic_discovery_fail_msg: "Failed to discover any idrac's with the dynamic range. Please check the range again"
no_bmc_found: 'No bmc found'

# Usage: mtms/update_db_static.yml
update_db_static_path: "{{ role_path }}/files/utils/extract_static_data.py"

# Usage: mtms/update_static_node_obj.yml
update_static_node_path: "{{ role_path }}/files/utils/update_node_objects.py"
