#  Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Check that the passwordless_ssh_config.yml exists
  ansible.builtin.stat:
    path: "{{ passwordless_ssh_config_file }}"
  register: stat_result

- name: Fail if passwordless_ssh_config.yml file doesn't exist
  ansible.builtin.fail:
    msg: "{{ fail_msg_passwordless_ssh_config_file }}"
  when: not stat_result.stat.exists

- name: Check passwordless_ssh_config.yml file is encrypted
  ansible.builtin.command: cat {{ passwordless_ssh_config_file }}
  changed_when: false
  register: config_content
  no_log: true

- name: Decrpyt passwordless_ssh_config.yml
  ansible.builtin.command: >-
    ansible-vault decrypt {{ passwordless_ssh_config_file }}
    --vault-password-file {{ vault_filename }}
  changed_when: false
  when: "'$ANSIBLE_VAULT;' in config_content.stdout"

- name: Include variable file passwordless_ssh_config.yml
  ansible.builtin.include_vars: "{{ passwordless_ssh_config_file }}"
  no_log: true

- name: Create ansible vault key
  ansible.builtin.set_fact:
    vault_key: "{{ lookup('password', '/dev/null chars=ascii_letters') }}"
  when: "'$ANSIBLE_VAULT;' not in config_content.stdout"

- name: Save vault key
  ansible.builtin.lineinfile:
    path: "{{ vault_filename }}"
    line: "{{ vault_key }}"
    mode: "{{ vault_file_perm }}"
    owner: root
    create: true
  when: "'$ANSIBLE_VAULT;' not in config_content.stdout"
