{{- if and .Values.enabled .Values.rbac.create }}
{{- $ns := include "victoria-metrics.namespace" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ $ns }}
  labels:
    {{- include "victoria-metrics.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ $ns }}
  labels:
    {{- include "victoria-metrics.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ $ns }}
  labels:
    {{- include "victoria-metrics.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ $ns }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.serviceAccountName }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
    {{- include "victoria-metrics.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
    {{- include "victoria-metrics.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ $ns }}
{{- end }}
