# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Validate security input parameters
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Validate security input parameters
      ansible.builtin.include_role:
        name: security_validation
        tasks_from: validation_status_check.yml
  tags: freeipa, ldap, test

- name: Gather facts from all the nodes
  hosts: manager, compute, login

#- name: Validate repo file and subscription
#  hosts: manager, login, compute
#  gather_facts: false
#  roles:
#    - repo_validation
#  tags: freeipa, ldap

- name: Add hosts to compute and login nodes
  hosts: manager, login, compute
  gather_facts: false
  any_errors_fatal: true
  roles:
    - hostname_validation
  tags: freeipa

- name: Validate hostname
  hosts: manager, login, compute
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: Validate hostname
      ansible.builtin.include_role:
        name: hostname_validation
        tasks_from: validate_hostname.yml
  tags: freeipa, ldap, test

- name: Apply login common installation and config
  hosts: manager, login, compute
  any_errors_fatal: true
  gather_facts: false
  roles:
    - login_common
  tags: freeipa

- name: Apply login server installation and config
  hosts: manager
  gather_facts: false
  roles:
    - login_server
  tags: freeipa

- name: Install FreeIPA client on login and compute nodes
  hosts: login, compute
  gather_facts: false
  roles:
    - login_node
  tags: freeipa

# - name: Validate ldap server inputs
#   hosts: localhost
#   any_errors_fatal: true
#   gather_facts: false
#   roles:
#     - ldap_validation
#   tags: test

# - name: Apply ldap server installation and config
#   hosts: manager
#   roles:
#     - ldap_server
#   tags: test

# - name: Apply ldap server installation and config
#   remote_user: root
#   hosts: manager
#   vars:
#     - ldaptoolbox_openldap_database_olcLimits:
#          - "dn.base=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth size=unlimited  time=unlimited"
#     # No replication
#     - ldaptoolbox_openldap_syncrepl: []
#   roles:
#     - /opt/omnia/ldap/ansible-role-ldaptoolbox-openldap
#   tags: test

- name: Setup LDAP server domain
  hosts: manager
  tasks:
    - name: Include domain setup task
      ansible.builtin.include_role:
        name: ldap_server
        tasks_from: set_domain.yml

# - name: Apply ldap client installation and config
#  hosts: manager, compute, login
#  gather_facts: false
#  roles:
#    - ldap_client
#  tags: ldap

- name: Configure secure login
  hosts: login
  gather_facts: false
  roles:
    - secure_login_node
