#  Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: include_vars.yml
base_vars_filepath: "{{ playbook_dir }}/input_params/base_vars.yml"
rhsm_support_fail_msg: "Omnia supports redhat subscription management only when rhsm_support is set to true in base_vars.yml"
rhsm_vars_filename: "{{ playbook_dir }}/input_params/rhsm_vars.yml"
rhsm_credentials_fail_msg: "redhat_subscription_username and redhat_subscription_password are mandatory 
                            fields if redhat_subscription_method is set to portal"
rhsm_portal_vars_me: "redhat_subscription_username and redhat_subscription_password will not be used 
                      when redhat_subscription_method is set to satellite"
rhsm_satellite_vars_me: "redhat_subscription_activation_key and redhat_subscription_org_id will not be 
                        used when redhat_subscription_method is set to portal"
rhsm_activation_key_fail_msg: "redhat_subscription_activation_key is mandatory field if 
                                redhat_subscription_method is set to satellite"
rhsm_org_id_fail_msg: "redhat_subscription_org_id must be used along with redhat_subscription_activation_key"

# Usage: setup_rhsm_role.yml
rhsm_git_repo: "https://github.com/openstack/ansible-role-redhat-subscription.git"
rhsm_git_stable_commit: "0f7ac2a"
rhsm_git_dest: "{{ playbook_dir }}/roles/control_plane_rhsm/files/openstack-rhsm"
portal_file_path: "{{ playbook_dir }}/roles/control_plane_rhsm/files/openstack-rhsm/tasks/portal.yml"

# Usage: redhat_subscription.yml
hosts_file: /etc/hosts
