# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Create log folder for jobs
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ vault_file_perm }}"
  loop: "{{ job_log_path }}"
  when: item.flag

- block:
    - name: Fetch ansible-playbook path
      command: whereis ansible-playbook
      changed_when: false
      register: ansible_playbook_path

    - name: Create cron job for node inventory
      cron:
        name: node inventory job runs every 1 hour
        special_time: hourly
        job: "{{ ansible_playbook_path.stdout.split(' ')[1] }} {{ playbook_dir }}/collect_node_info.yml  >> {{ collect_node_info_log }}"
    
    - name: Configure devices
      block:
        - name: Create cron job for device inventory
          cron:
            name: device inventory job runs every day
            special_time: daily
            job: "{{ ansible_playbook_path.stdout.split(' ')[1] }} {{ playbook_dir }}/collect_device_info.yml  >> {{ collect_device_info_log }}"

        - name: Execute device inventory job
          block:
            - name: Execute collect_device_info.yml
              shell: ansible-playbook {{ playbook_dir }}/collect_device_info.yml >> {{ collect_device_info_log }}
              changed_when: true
              register: collect_device_info_job

            - debug:
                var: collect_device_info_job
          rescue:
            - name: Warning message for device inventory job
              debug:
                msg: "{{ device_inventory_job_warn_msg }}. Error: {{ collect_device_info_job.stderr }}"

        - name: Execute node inventory job
          block:
            - name: Execute collect_node_info.yml
              shell: ansible-playbook {{ playbook_dir }}/collect_node_info.yml >> {{ collect_node_info_log }}
              changed_when: true
              register: collect_node_info_job
          rescue:
            - name: Warning message for node inventory job
              debug:
                msg: "{{ node_inventory_job_warn_msg }}. Error: {{ collect_node_info_job.stderr }}"
          when: network_interface_type == 'lom'
      when: device_support_status or network_interface_type == 'lom'
  when: not awx_web_support