apiVersion: v1
kind: Pod
metadata:
  name: tensorrt-client
spec:
  containers:
  - image: nvcr.io/nvidia/tensorrtserver:20.01-py3-clientsdk
    imagePullPolicy: IfNotPresent
    name: tensorrt-client
    volumeMounts:
      - mountPath: /work
        name: work-volume
    command: [ "/bin/bash" ]
    args: ["-c", "while true; do sleep 120; done;"]
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
  imagePullSecrets:
  - name: ngc-secret 
  volumes:
  - name: work-volume
    hostPath:
      # NFS mount on computes
      path: /home/root/
      type: Directory
