# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Validate roce_plugin input parameters
  hosts: localhost
  connection: local
  tasks:
    - name: Validate input parameters
      ansible.builtin.include_role:
        name: k8s_roce_deploy
        tasks_from: validations.yml

- name: Deploy pre-requisites of roce pod on top of k8s control plane
  hosts: kube_control_plane
  gather_facts: true
  roles:
    - k8s_roce_deploy

- name: Load drivers on kube_nodes
  hosts: kube_node
  tasks:
    - name: Load drivers on kube_nodes
      ansible.builtin.include_role:
        name: k8s_roce_deploy
        tasks_from: load_drivers.yml

- name: Deploy rocepod on top of k8s control plane
  hosts: kube_control_plane
  tasks:
    - name: Deploy rocepod
      ansible.builtin.include_role:
        name: k8s_roce_deploy
        tasks_from: deploy_roce_pod.yml
