# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Include vars file of inventory role
  ansible.builtin.include_vars: "{{ role_path }}/../../../input/network_config.yml"

# Filter inventories for IB connected nodes
- name: Setup nfs client on nodes with infiniband support
  ansible.builtin.include_tasks: setup_inventories.yml

# Set nfs_mlnx_ofed status to true if atleast one node is present in redhat_rocky_inventory
- name: Set nfs_mlnx_ofed status to true if atleast one node is present in redhat_rocky_inventory
  ansible.builtin.set_fact:
    nfs_mlnx_ofed: true
  when: groups['redhat_rocky_inventory'] | default("", true) | length | int > 0

# Setup nfs server when nfs_mlnx_ofed status is set to true
- name: Setup NFS Server for Rhel compute nodes
  block:
    - name: Setup nfs server on localhost
      ansible.builtin.include_tasks: setup_nfs_server.yml

    - name: Setup mlnx_repo on localhost
      ansible.builtin.include_tasks: setup_mlnx_ofed_repo.yml

  when: nfs_mlnx_ofed is true
