# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Include vars file of inventory role
  ansible.builtin.include_vars: "{{ role_path }}/../../../input/network_config.yml"

- name: Install mlnx_ofed if not already installed
  when:
    - os_supported_rhel in ansible_facts['distribution'] | lower
      or os_supported_rocky in ansible_facts['distribution'] | lower
  block:
    - name: Check status of openibd service
      ansible.builtin.command: systemctl status openibd
      changed_when: false
      failed_when: false
      register: openibd_status

    - name: Setup nfs-client if not already installed
      when: "'Active: active' not in openibd_status.stdout"
      block:
        - name: Setup nfs client on nodes with infiniband support
          ansible.builtin.include_tasks: setup_nfs_client.yml
          when:
            - hostvars['localhost']['nfs_mlnx_ofed'] is true

        - name: Install mlnx_ofed on redhat nodes
          ansible.builtin.include_tasks: install_mlnx_ofed.yml

- name: Install mlnx_ofed on leap nodes
  ansible.builtin.include_tasks: install_mlnx_leap.yml
  when: os_supported_leap in ansible_facts['distribution'] | lower
