# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Initialise ib node status
  ansible.builtin.set_fact:
    ib_node_status: false

- name: Initialise redhat status
  ansible.builtin.set_fact:
    redhat_status: false

- name: Check Mellanox card status
  ansible.builtin.shell: >
    set -o pipefail && \
    lspci -v | grep Mellanox
  changed_when: false
  register: lspci_status
  failed_when: false

- name: Update ib node status
  ansible.builtin.set_fact:
    ib_node_status: true
  when: "'Mellanox' in lspci_status.stdout"

- name: Update OS name if Rhel node
  ansible.builtin.set_fact:
    redhat_status: true
  when: ansible_facts['distribution'] | lower == os_supported_rhel

- name: Validate rhsm status on redhat nodes having ib connectivity
  block:
    - name: Validate redhat subscription status
      ansible.builtin.include_tasks: validate_rhsm.yml
  rescue:
    - name: Warning - redhat subscription not enabled
      ansible.builtin.pause:
        seconds: "{{ warning_wait_time }}"
        prompt: "{{ subscription_warning_msg }}"
  when:
    - redhat_status
    - ib_node_status
