# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

slurm_telemetry_support: false

# Usage: include_provision_config.yml
provision_config_file: "{{ role_path }}/../../../input/provision_config.yml"
fail_msg_provision_config_file: "provision_config.yml file doesn't exist."
provision_vault_filename: "{{ role_path }}/../../../input/.provision_vault_key"

# Usage: pre-requisites.yml
os_supported_leap: "leap"
selinux_warning: "Warning! SELinux status is disabled by user. No SELinux policy is loaded"
telemetry_config_file: "{{ role_path }}/../../../input/telemetry_config.yml"
fail_msg_telemetry_config_file: "telemetry_config.yml file doesn't exist."
pip_packages:
  - openshift
  - omsdk
  - PyMySQL
mysqldb_collection_name: community.mysql:3.1.0
retry_count: 3
rhel_epel_repo8: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
max_retries: 20
os_supported_redhat: "redhat"
rhel_code_ready_repo: codeready-builder-for-rhel-8-x86_64-rpms

# Usage: validate_telemetry_config.yml
success_msg_k8s_pod_network_cidr: "Appliance k8s pod network cidr validated"
fail_msg_k8s_pod_network_cidr: "Failed. Incorrect appliance k8s pod network cidr provided in input/telemetry_config.yml"
folder_perm: '644'
vault_file_perm: '0644'
idrac_telemetry_support_success_msg: "idrac_telemetry_support validated"
idrac_telemetry_support_fail_msg: "Failed. idrac_telemetry_support only accepts boolean
                                    values true or false"
omnia_telemetry_support_fail_msg: "Failed. omnia_telemetry_support accepts boolean value true or false"
visualization_support_success_msg: "visualization_support_ validated"
visualization_support_fail_msg: "Failed. visualization_support accepts boolean value true or false"
idrac_omnia_telemetry_support_false_warn_time: 10
idrac_omnia_telemetry_support_warn_msg: "Warning. Both idrac_telemetry_support and omnia_telemetry_support are false"
vault_filename: "{{ role_path }}/../../../input/.telemetry_vault_key"
login_vars_fail_msg: "Username/password validation in telemetry_config.yml failed. Please check the requirements."

# Usage: validate_idrac_telemetry.yml
min_length_idrac: 3
max_length: 30
fail_timezone_msg: "Failed. Incorrect timezone provided. Please check the file timezone.txt in provision/roles/provision_validation/files/timezone.txt folder"
idrac_credentials_fail_msg: "idrac_username and idrac_password must be provided in telemetry_config.yml."
idrac_inventory_msg: "idrac group is not present in inventory file. Playbook will check for /opt/omnia/provisioned_idrac_inventory"
idarc_inventory_path: "/opt/omnia/provisioned_idrac_inventory"
idrac_file_status: "There is no inventory present under /opt/omnia/provisioned_idrac_inventory.
                    Please provide inventory with idrac group or create an inventory /opt/omnia/provisioned_idrac_inventory"
idrac_exec_msg: "Since the absence of idrac group in inventory and existence of /opt/omnia/provisioned_idrac_inventory file.
                   iDRAC telemetry execution will be skipped"
advanced_vars_fail_msg: "Please give correct inputs for advanced configurations (mysqldb credentials) for idrac telemetry in telemetry_config.yml.
                  Advanced configurations include inputs related to mysqldb for storing idrac credentials"
validation_error_msg_format_start_range: "Invalid Format! pod_external_ip_start_range accepts this format x.y.240.100"
validation_error_msg_format_end_range: "Invalid Format! pod_external_ip_end_range accepts this format x.y.240.105"
validation_error_msg_4_octets: "Validation Error: The pod external IP range should have 4 octets."
validation_error_msg_octet_range: "Validation Error: The third and fourth octets of the pod external IP should be between 0 and 255."
validation_error_msg_octet_order: "Validation Error: The third octet of the pod external IP start range should be less than or equal
                                    to the third octet of the end range."
validation_error_msg_same_third_octet_order: "Validation Error: The fourth octet of the pod external IP start range should be
                                               less than the fourth octet of the end range when the third octets are the same."
validation_success_msg_format_start_range: "pod_external_ip_start_range format is valid."
validation_success_msg_format_end_range: "pod_external_ip_end_range is valid."
validation_success_msg_4_octets: "Pod external IP range has 4 octets."
validation_success_msg_octet_range: "Third and fourth octets of pod external IP are within the valid range."
validation_success_msg_octet_order: "Third octet of the pod external IP start range is less than or equal to the third octet of the end range."
validation_success_msg_same_third_octet_order: "Fourth octet of the pod external IP start range is less than the fourth octet of the end range
                                                 when the third octets are different."

# Usage: validate_omnia_telemetry.yml
min_interval: 60
max_interval: 3600
omnia_telemetry_collection_interval_fail_msg: "Failed. omnia_telemetry_collection_interval accepts integer values between 60 to 3600 seconds"
collect_regular_metrics_fail_msg: "Failed. collect_regular_metrics accepts values true or false"
collect_health_check_metrics_fail_msg: "Failed. collect_health_check_metrics accepts values true or false"
collect_gpu_metrics_fail_msg: "Failed. collect_gpu_metrics accepts values true or false"
all_omnia_telemetry_support_false_fail_msg: "Failed. One of Regular, health-check or GPU metric collector must be true if omnia_telemetry_support is true"
fuzzy_offset_fail_msg: "Failed. fuzzy_offset accepts integer values greater than equal to 60 and less than omnia_telemetry_collection_interval value"
metric_collection_timeout_fail_msg: "Failed. metric_collection_timeout accepts integer values greater than 0 and less than omnia_telemetry_collection_interval"
telemetry_config_syntax_fail_msg: "Failed. Syntax errors present in telemetry_config.yml. Fix errors and re-run playbook again. Common syntax Errors:
indentation errors, improper quotes, improper space or tab, missing colon, missing comma etc. "
inventory_fail_msg: "Inventory comprising manager and compute groups should be passed when omnia_telemetry_support is true."
inventory_success_msg: "Inventory is passed."
manager_group_fail_msg: "Manager group should contain exactly 1 node"
compute_group_fail_msg: "Compute group should contain atleast 1 node"
login_group_fail_msg: "Login group should contain exactly 1 node"

# Usage: set_docker_os.yml
docker_rocky_os: "8.5"
slurm_telemetry_dockerfile_path: "{{ playbook_dir }}/roles/slurm_telemetry/files/Dockerfile"

# Usage: validate_grafana.yml
fail_msg_grafana_credentials: "Failed. Incorrect grafana_username or grafana_password format provided"
mount_validation_msg: "Make sure mount location value is not null"
min_length_grafana: 5
