# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: clean_provision_setup.yml
xcat_packages_path: "/opt/xcat/share/xcat/tools/go-xcat"
xcat_cert_path: "/root/.xcat"
xcat_data_files_path: "/etc/xcat"
fstab_path: "/etc/fstab"
xcat_del_files:
  - "/install"
  - "/tftpboot"
  - "/etc/yum.repos.d/xCAT-*"
  - "/etc/sysconfig/xcat"
  - "/etc/apache2/conf.d/xCAT-*"
  - "/etc/logrotate.d/xCAT-*"
  - "/etc/rsyslogd.d/xCAT-*"
  - "/var/log/xcat"
  - "/opt/xcat/"
  - "/mnt/xcat"
  - "{{ playbook_dir }}/../provision/roles/xcat_repo_manipulate/files/pxe_mapping_file.csv"
  - /root/xcat-dbback
  - /opt/racadm
  - /opt/omnia/
  - /var/lib/dhcpd/dhcpd6.leases
  - /var/lib/dhcpd/dhcpd.leases~
  - /var/lib/dhcpd/dhcpd.leases.rpmsave
  - /var/lib/dhcpd
  - /var/lib/dhclient
  - /etc/dhcp/dhcpd.conf.rpmsave
  - /etc/dhcp/dhcpd.conf.xcatbak
  - /etc/dhcp/dhclient.conf
pg_dir_path: "/var/lib/pgsql"
omnia_dir: "/opt/omnia"
file_permission: "754"
xcat_download_files:
  - /root/xcat
  - /etc/yum.repos.d/xcat-core.repo
  - /etc/yum.repos.d/xcat-dep.repo
xcat_package: xCAT
postgres_packages:
  - postgresql*
  - perl-DBD-Pg
control_plane_os_redhat: "redhat"

# Usage:clean_telemetry_setup.yml
exports_path: /etc/exports
exports_regexp:
  - "/install"
  - "/tftpboot"
  - "/var/nfs_repo"
crio_socket: /var/run/crio/crio.sock
grafana_folders:
  - "{{ mount_location }}grafana"
  - "{{ mount_location }}github-grafana-plugins"
telemetry_folders:
  - "{{ mount_location }}iDRAC-Telemetry-Reference-Tools/"
  - "{{ mount_location }}iDRAC-Telemetry-Scripting/"
database_folders:
  - "{{ mount_location }}mysqldb/"
  - "{{ mount_location }}timescaledb/"
metallb_files:
  - "/var/lib/ipaddresspool.yaml"
  - "/var/lib/l2advertisement.yaml"

# Usage: clean_docker_registry.yml
docker_registry_file: /etc/systemd/system/docker-registry.service
docker_packages: "docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras"
docker_del_files:
  - /var/lib/docker
  - /var/lib/containerd
  - /opt/omnia/containerd
  - /etc/yum.repos.d/docker-ce.repo
  - /docker-registry

# Usage:include_telemetry_config.yml
telemetry_config_file: "{{ role_path }}/../../../input/telemetry_config.yml"
telemetry_vault_filename: "{{ role_path }}/../../../input/.telemetry_vault_key"
telemetry_config_syntax_fail_msg: "Failed.Syntax errors present in telemetry_config.yml.Fix errors and re-run playbook again."
vault_file_perm: '0644'
