# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Saving management station os
  ansible.builtin.set_fact:
    mgmt_os: "{{ ansible_facts['distribution'] | lower }}"

- name: Check SELinux Status
  when: os_supported_leap not in mgmt_os
  block:
    - name: Fetch SElinux mode
      ansible.builtin.command: sestatus
      register: sestatus_current
      changed_when: false

    - name: Check SELinux status
      ansible.builtin.debug:
        msg: "{{ selinux_warning }}"
      when: '"SELinux status:                 disabled" in sestatus_current.stdout_lines'

    - name: Set SElinux to permissive mode
      ansible.builtin.command: setenforce 0
      when: '"SELinux status:                 enabled" in sestatus_current.stdout_lines'

- name: Install openshift using pip3
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items: "{{ pip_packages }}"

- name: Install sqldb collection
  ansible.builtin.command: ansible-galaxy collection install "{{ mysqldb_collection_name }}"
  changed_when: false

- name: Login to docker
  block:
    - name: Docker login
      ansible.builtin.command: docker login -u {{ docker_username }} -p {{ docker_password }}
      changed_when: true
      register: docker_login_output
      retries: 10
      delay: 5
      until: docker_login_output is not failed
      when: docker_username or docker_password
      no_log: true
  rescue:
    - name: Warning - docker login failed
      ansible.builtin.debug:
        msg: "Warning: {{ docker_login_output.stderr }}"

- name: Docker login check
  ansible.builtin.fail:
    msg: "{{ docker_login_fail_msg }}"
  when: docker_login_output is failed
