# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Check existence of pre-required tools on management station
  block:
    - name: Check grafana service
      ansible.builtin.command: kubectl get svc -n grafana
      register: grafana_svc_register
      failed_when: "'grafana' not in grafana_svc_register.stdout"
      changed_when: false
  rescue:
    - name: Grafana needs to be installed
      ansible.builtin.fail:
        msg: "{{ installation_required }}"

# Fetching grafana mount point from control plane
- name: Check for grafana folder existence
  ansible.builtin.stat:
    path: "{{ grafana_conf_path }}"
  register: grafana_file_status

- name: Fail if grafana_conf file doesn't exist
  ansible.builtin.fail:
    msg: "{{ installation_required }}"
  when: not grafana_file_status.stat.exists

- name: Fetch grafana mount point
  ansible.builtin.set_fact:
    mount_location: "{{ lookup('ini', 'mount_point section=grafana_svc file=/opt/omnia/.data/grafana_svc_details.ini') }}"
