#!/bin/bash
################################################################################################################
#  omnia_rocm:
#      Install ROCm on all the cluster nodes using AMD ROCm packages
#
#################################################################################################################
echo "--------------------------" >> /var/log/xcat/xcat.log
echo "Checking for AMD cards" >> /var/log/xcat/xcat.log
validate_ubuntu_os="$(cat /etc/os-release | grep 'ID=ubuntu' | wc -l)"
amd_check=`lspci|grep "Display controller: Advanced Micro Devices, Inc. \[AMD/ATI]"`
validate_ubuntu_os="$(cat /etc/os-release | grep 'ID=ubuntu' | wc -l)"
if [[ $validate_ubuntu_os == "1" ]]; then
  if [[ $amd_check == *"Advanced Micro Devices"* ]]
  then
    echo "Starting CUDA installation" >> /var/log/xcat/xcat.log
    sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)" -y
    sudo apt install amdgpu-dkms -y
    sudo apt install rocm-hip-sdk -y
    reboot
    echo "ROCm installation completed" >> /var/log/xcat/xcat.log
  else
    echo "AMD cards not found" >> /var/log/xcat/xcat.log
  fi
  echo "-----------------------------" >> /var/log/xcat/xcat.log
fi

if [[ $amd_check == *"Advanced Micro Devices"* ]]
then
  echo "Starting CUDA installation" >> /var/log/xcat/xcat.log
  dnf install kernel-headers kernel-devel -y
  dnf clean all
  dnf install amdgpu-dkms -y
  dnf -y install rocm-hip-sdk
  reboot
  echo "ROCm installation completed" >> /var/log/xcat/xcat.log
else
  echo "AMD cards not found" >> /var/log/xcat/xcat.log
fi
echo "-----------------------------" >> /var/log/xcat/xcat.log
