# Copyright 2021 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# vars file for provision

#Usage: mapping_file.yml
temp_host_mapping_file: "{{ role_path }}/files/new_host_mapping_file.csv"

#Usage: check_prerequisite.yml
iso_name: CentOS-7-x86_64-Minimal-2009.iso
iso_fail: "Iso file not found. Download and copy the iso file to omnia/control_plane/roles/provision_cobbler/files"

# Usage: provision_password.yml
provision_encrypted_dest: ../files/
login_file: "{{ role_path }}/../../input_params/login_vars.yml"
base_file: "{{ role_path }}/../../input_params/base_vars.yml"
login_vault_file: "{{ role_path }}/../../input_params/.login_vault_key"
username: cobbler
user_mode: 0644
host_nic:
 - em1
 - em2
 - em3
 - em4
 - p4p1
 - p4p2
 - p3p1
 - p3p2
 - p2p1
 - p2p2
 - p1p2
 - p1p1

# Usage: cobbler_image.yml
cobbler_image_name: cobbler
cobbler_image_tag: latest

# Usage: main.yml
message_skipped: "Installation Skipped: Cobbler instance is already running in your system"
message_installed: "Installation Successful"

# Usage: mount_iso.yml
iso_dir_name: iso
