# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: main.yml
os_supported_leap: "leap"
os_supported_rocky: "rocky"
os_supported_rhel: "redhat"

# Usage: pre-requisites.yml
mlnx_ofed_version_success: "mlnx_ofed_version validated successfully."
mlnx_ofed_version_fail: "mlnx_ofed_version validation failed. Make sure the version entered is present in {{ mlnx_ofed_repository }}"

# Usage: validations.yml
inactive_msg1: "1. Host {{ ansible_ssh_host }} is not subscribed to redhat"
inactive_msg2: "2. Host {{ ansible_ssh_host }} didnt have baseos and appstream repos enabled."
fail_mlnx_file_type: "The given file is not a .tgz file."
fail_mlnx_file: "File doesn't exist at given path: "
uri_status_code: 200
fail_mlnx_url: "Please check mlnx_ofed_version. The tar file for mentioned version should be available in
 https://network.nvidia.com/products/infiniband-drivers/linux/mlnx_ofed/"
mlnx_ofed_add_kernel_support_fail_msg: "mlnx_ofed_add_kernel_support variable can only be set to true or false."

# Usage: setup_nfs_server.yml
nfs_utilities:
  - nfs-utils
  - firewalld
nfs_services:
  - rpcbind
  - nfs-server
  - firewalld
firewall_services:
  - nfs
  - mountd
  - rpc-bind
firewall_ports:
  - 111/tcp
  - 111/udp
  - 2049/tcp
  - 2049/udp
  - 20048/tcp
  - 20048/udp

# Usage: setup_mlnx_ofed_repo.yml
mlnx_ofed_nfs_path: "/opt/mlnx_ofed"
mlnx_ofed_nfs_permissions: '0777'
exports_file: "/etc/exports"
server_export_options: "rw,sync,no_root_squash"
mlnx_ofed_filepath: "{{ mlnx_ofed_nfs_path + '/mlnx_ofed_file.tgz' }}"
mlnx_ofed_folder: "{{ mlnx_ofed_nfs_path + '/mlnx_ofed_linux/' }}"

# Usage: setup_nfs_client.yml
nfs_packages:
  - nfs-utils
  - nfs4-acl-tools
client_mount_options: "nosuid,rw,sync,hard,intr"
server_ip: "{{ hostvars['localhost']['server_ip'] }}"

# Usage: install_mlnx_ofed.yml
ofed_packages:
  - tar
  - libtool
  - kernel-rpm-macros
  - createrepo
  - python36-devel
  - lsof
  - redhat-rpm-config
  - rpm-build
  - gcc
  - gtk2
  - atk
  - cairo
  - gcc-gfortran
  - tcsh
  - tcl
  - tk
  - kernel-modules-extra
  - elfutils-libelf-devel
  - make
mlnx_ofed_filename: "{{ hostvars['localhost']['mlnx_ofed_filename'] }}"
fail_ib_nic: "IB connectivity could not be found on host: {{ ansible_ssh_host }}"

# Usage: install_mlnx_leap.yml
infiniband_leap:
  - rdma-core
  - librdmacm1
  - libibmad5
  - libibumad3
  - infiniband-diags

# Usage: install_mlnx_rocky.yml
infiniband_rocky:
  - "@Infiniband Support"
  - infiniband-diags
  - perftest
  - qperf
