{{- if and .Values.enabled (not .Values.secrets.existingSecret) }}
{{- $ns := include "idrac.namespace" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: idrac-mysql-credentials
  namespace: {{ $ns }}
  labels:
    {{- include "idrac.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysqldb_user: {{ .Values.secrets.mysqlUser | default "telemetry" | quote }}
  mysqldb_password: {{ .Values.secrets.mysqlPassword | default (randAlphaNum 16) | quote }}
  mysqldb_root_password: {{ .Values.secrets.mysqlRootPassword | default (randAlphaNum 16) | quote }}
{{- end }}
