# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# OS version that is installed on nodes like RHEL 8.4, 8.5, or 8.6
# This is required to update the object of that os to install/update packages 
os_version: ""

# This variable accepts the directory in which the package RPMs are downloaded
# eg: /install/custom/rhels8.6.0/x86_64/
package_dir: ""

# This variable accepts the location path for package list file 
# For other packagelist, file type should be - (xxx.otherpkgs.pkglist)
# For os packagelist, file type should be - (xxx.pkglist)
# All packages in this list will be installed/updated on remote nodes 
package_list: ""

# This variable accepts type of package that must be installed/updated on remote nodes
# This value can be "os" or "other"
# "os" - If packages to be installed/updated are os packages which are available in appstream or baseos
# "other" - If packages to be installed/updated are not part of os repos appstream or baseos
package_type: ""

# This variable will contain list of all nodes on which packages must installed/updated
# Node names can be fetched from postgres db
# By default packages will be installed/updated on all nodes
# eg: node1,node2,node3,node4 or node1-node5
# Default: all
nodelist: "all"

# This boolean variable determines if remote nodes are required to be rebooted
# If true then all node in node_list will get rebooted
# Default: true
reboot_required: true 
