# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Create group for provision container
  hosts: localhost
  connection: local
  tasks:
    - name: Create omnia_provision group
      ansible.builtin.add_host:
        hostname: 'omnia_provision'
        ansible_host: 'localhost'
        ansible_port: "2223"
        groups: 'omnia_provision'
        ansible_python_interpreter: "python3"

    - name: Decrypt provision_credentials_config.yml
      ansible.builtin.include_role:
        name: discovery_validations/common
        tasks_from: encrypt_provision_credentials_config.yml

- name: Validate discovery parameters
  hosts: omnia_provision
  connection: ssh
  tasks:
    - name: Validate discovery parameters
      ansible.builtin.include_role:
        name: discovery_validations/common

- name: Encrypyt provision_credentials_config.yml
  hosts: localhost
  connection: local
  tasks:
    - name: Encrypyt provision_credentials_config.yml
      ansible.builtin.include_role:
        name: discovery_validations/common
        tasks_from: encrypt_provision_credentials_config.yml

- name: Validate discovery parameters
  hosts: omnia_provision
  connection: ssh
  tasks:
    - name: Discovery roles of Omnia Infrastructure Manager for provisioning
      ansible.builtin.include_role:
        name: db_operations

    - name: Enter Omnia Infrastructure Manager details in cluster.nodeinfo table
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../utils/server_spec_update/roles/network_update"    # noqa: role-name[path]
        tasks_from: add_nic_db.yml
      when: add_network_status

    - name: Configure xcat
      ansible.builtin.include_role:
        name: configure_xcat/common         # noqa: role-name[path]

    - name: Discover all nodes
      ansible.builtin.include_role:
        name: discovery_mechanism/common     # noqa: role-name[path]

- name: Update kernel parameters
  hosts: "all:!localhost,!omnia_provision"
  connection: local
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../input/server_spec.yml"
  roles:
    - role: os_update

- name: Discovery roles of Omnia Infrastructure Manager for provisioning
  hosts: omnia_provision
  connection: ssh
  roles:
    - role: postscripts/common             # noqa: role-name[path]
    - role: configure_os_image/common      # noqa: role-name[path]
    - role: monitor_thread

- name: Update metadata
  hosts: localhost
  connection: local
  roles:
    - role: metadata_update
