#  Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: promtail_image.yml
promtail_image_name: "promtail"
promtail_image_tag: "latest"
image_creation_retries: 20

# Usage: k8s_loki_pod.yml
loki_k8s_name: loki
loki_port: 3100
loki_image_name: docker.io/grafana/loki
loki_image_tag: 2.4.1
package_retry: 10

# Usage: configure_loki_grafana
pod_timeout: 30m
grafana_namespace: grafana

# Usage enable_buildkit.yml
image_retries: 5
delay_loki: 10
local_repo_config_path: "{{ role_path }}/../../../input/local_repo_config.yml"
buildkit_dir: "{{ repo_store_path }}/cluster/git/buildkit"

# Usage prereq.yml
sources_list_dest: /etc/apt/sources.list.d
docker_repo_temp: templates/docker_repo.j2
dir_mode: "755"
file_mode: "0644"
keyringsfile: /etc/apt/keyrings
docker_repo: https://download.docker.com/linux/centos/docker-ce.repo
docker_packages_ubuntu:
 - docker-ce={{ epoch_version }}
 - docker-ce-cli={{ epoch_version }}
 - docker-buildx-plugin
docker_packages_redhat:
 - docker-ce-24.0.4
 - docker-ce-cli-24.0.4
 - docker-buildx-plugin
cert_packages:
 - curl
 - ca-certificates
gpg_path: /etc/apt/keyrings/docker.asc
docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
