{{- if and .Values.enabled .Values.vast.enabled (not .Values.vast.credentials.existingSecret) }}
{{- $ns := include "external-sources.namespace" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: vast-telemetry-credentials
  namespace: {{ $ns }}
  labels:
    {{- include "external-sources.labels" . | nindent 4 }}
type: Opaque
{{- if eq .Values.vast.authMode "basic" }}
stringData:
  username: {{ .Values.vast.credentials.username | quote }}
  password: {{ .Values.vast.credentials.password | quote }}
{{- end }}
{{- end }}
