# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Initialize variables
  ansible.builtin.set_fact:
    os_image_status: false

- name: Check OS image is created
  ansible.builtin.shell: >
    set -o pipefail && \
    lsdef -t osimage | grep "{{ provision_os }}"
  changed_when: false
  failed_when: false
  register: os_image_check

- name: Set os_image_status to true
  ansible.builtin.set_fact:
    os_image_status: true
  when: provision_os in os_image_check.stdout

- name: Create OS image
  ansible.builtin.shell: source {{ xcat_env_path }} && copycds {{ iso_file_path }}
  changed_when: true
  when: not os_image_status

- name: Copy RHEL8 kickstart files to xcat configuration path
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ xcat_rhel8_path }}"

- name: Configure kickstart file - language
  ansible.builtin.replace:
    path: "{{ xcat_rhel8_tmpl }}"
    regexp: '^lang ks_language'
    replace: 'lang {{ language }}'

- name: Enable internet accesss in compute nodes
  block:
    - name: Add masquerade to public_nic zone
      ansible.builtin.command: firewall-cmd --zone={{ public_nic_zone }} --add-masquerade --permanent
      changed_when: true

    - name: Reload firewalld
      ansible.builtin.command: firewall-cmd --reload
      changed_when: true
  when: primary_dns | length > 1

- name: Disable repos
  ansible.builtin.lineinfile:
    path: "{{ xcat_rhel8_post_script }}"
    insertafter: '^(.*)echo "Disabling repos"'
    line: "    sed -i -e 's/enabled=1/enabled=0/' /etc/yum.repos.d/$repo_file"
  when: primary_dns | length < 1
