# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Save records to mapping file when both ib_ip and bmc_ip present - {{ item.admin_ip }}
  ansible.builtin.lineinfile:
    insertafter: EOF
    dest: "{{ mapping_file_dest }}"
    line: "{{ item.admin_ip }},{{ item.ib_ip }},{{ item.bmc_ip }},{{ item.hostname }}"
    mode: "{{ file_perm }}"
  when:
    - empty_ib_ip | int == 0
    - empty_bmc_ip | int == 0

- name: Save records to mapping file when empty_bmc_ip present - {{ item.admin_ip }}
  ansible.builtin.lineinfile:
    insertafter: EOF
    dest: "{{ mapping_file_dest }}"
    line: "{{ item.admin_ip }},{{ item.ib_ip }},null,{{ item.hostname }}"
    mode: "{{ file_perm }}"
  when:
    - empty_ib_ip | int == 0
    - empty_bmc_ip | int > 0

- name: Save records to mapping file when empty_ib_ip present - {{ item.admin_ip }}
  ansible.builtin.lineinfile:
    insertafter: EOF
    dest: "{{ mapping_file_dest }}"
    line: "{{ item.admin_ip }},null,{{ item.bmc_ip }},{{ item.hostname }}"
    mode: "{{ file_perm }}"
  when:
    - empty_ib_ip | int > 0
    - empty_bmc_ip | int == 0

- name: Save records to mapping file when empty_ib_ip and empty_bmc_ip present - {{ item.admin_ip }}
  ansible.builtin.lineinfile:
    insertafter: EOF
    dest: "{{ mapping_file_dest }}"
    line: "{{ item.admin_ip }},null,null,{{ item.hostname }}"
    mode: "{{ file_perm }}"
  when:
    - empty_ib_ip | int > 0
    - empty_bmc_ip | int > 0

- name: Check IP is host or not
  block:
    - name: Check for reachable node - {{ item.admin_ip }}
      ansible.builtin.command: ping -c1 {{ item.admin_ip }}
      register: ping_result
      changed_when: false
      failed_when: false

    - name: Refresh ssh-key - {{ item.admin_ip }}
      ansible.builtin.command: ssh-keygen -R {{ item.admin_ip }}
      changed_when: false
      failed_when: false
      when: ping_search_key not in ping_result.stdout

    - name: Verify whether passwordless ssh is set on the remote host - {{ item.admin_ip }}
      ansible.builtin.command: sshpass ssh -o "PasswordAuthentication=no" root@{{ item.admin_ip }} 'hostname'
      register: ssh_output
      async: 15
      poll: 5
      failed_when: false
      changed_when: false
      when: ping_search_key not in ping_result.stdout
  when: item.admin_ip is defined

- name: Create group node_inventory with admin_ip - {{ item.admin_ip }}
  ansible.builtin.add_host:
    name: "{{ item.admin_ip }}"
    groups: "node_inventory"
  when:
    - item.admin_ip is defined
    - ping_search_key not in ping_result.stdout
    - ssh_output.stderr is defined
    - ssh_output.stdout is defined
    - ssh_search_key not in ssh_output.stderr | lower
    - ssh_output.stdout | length > 2
