- name: Upgrade Master
  hosts: masters
  serial: 1
  vars_files:
          - variable.yml
  tasks:
       - name: one
         include_tasks: upgrade_master.yml

- name: Upgrade Node
  hosts: workers
  serial: 1
  vars_files:
               - variable.yml
  tasks:
       - name: two
         include_tasks: upgrade_node.yml