{{- if .Values.enabled }}
{{- $ns := include "ldms.namespace" . -}}
{{- if and .Values.secrets.createOvisAuth (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: ldms-ovis-auth
  namespace: {{ $ns }}
  labels:
    {{- include "ldms.labels" . | nindent 4 }}
type: Opaque
stringData:
  secretword: {{ .Values.auth.secretWord | default (randAlphaNum 32) | quote }}
{{- end }}
---
{{- if and .Values.secrets.createMungeKey (not .Values.munge.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: ldms-munge-key
  namespace: {{ $ns }}
  labels:
    {{- include "ldms.labels" . | nindent 4 }}
type: Opaque
stringData:
  munge.key: {{ randAlphaNum 64 | quote }}
{{- end }}
{{- end }}
