{{- if .Values.enabled }}
{{- $ns := include "ldms.namespace" . -}}
apiVersion: v1
kind: Service
metadata:
  name: ldms-aggregator
  namespace: {{ $ns }}
  labels:
    app: ldms-aggregator
    {{- include "ldms.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: ldms
      port: {{ .Values.aggregator.port }}
      protocol: TCP
  selector:
    app: ldms-aggregator
{{- end }}
