---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  deployment_type: awx

  #tower_hostname:
  #tower_secret_key_secret:

  #tower_extra_volumes:

  #tower_admin_user: admin
  #tower_admin_email:
  #tower_admin_password_secret:

  tower_ingress_type: Ingress
  #tower_ingress_type:
  #tower_loadbalancer_protocol:
  #tower_loadbalancer_port:

  #tower_image_pull_secret:

  tower_postgres_storage_class: nfs-client

  tower_projects_persistence: true
  tower_projects_use_existing_claim: "_Yes_"
  tower_projects_existing_claim: awx-pv-claim
  tower_projects_storage_class: manual
  tower_projects_storage_size: 10Gi
  tower_projects_storage_access_mode: RWO

  tower_ee_images:
    - name: custom-awx-ee
      image: localhost/custom-awx-ee