#  Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Search schema
  ansible.builtin.command: ldapsearch -Y EXTERNAL -H ldapi:/// -b cn=schema,cn=config
  changed_when: false
  register: schema_output

- name: Verify and modify ldap schema
  when: schema_output is not search("ssh")
  block:
      - name: Modify schema
        ansible.builtin.command: ldapadd -Y EXTERNAL -H ldapi:/// -f "{{ role_path }}/files/addpubkeys.ldif"
        changed_when: false
